{% set name = "tangram_popmusicgui" %}


package:
  name: {{ name|lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - pychimera     >=0.2.6
    - libtangram

about:
  home: http://github.com/insilichem/tangram_popmusicgui
  license: MIT
  license_family: MIT

  summary: 'Depict and apply the predictions made by PoPMuSiC calculations in UCSF Chimera'

  description: |
    Depict and apply the predictions made by PoPMuSiC calculations in UCSF Chimera
  doc_url: http://tangram-suite.readthedocs.io/en/latest/tangram_popmusicgui.html
  dev_url: https://github.com/insilichem/tangram_popmusicgui


